# Generated by Django 4.2.16 on 2026-05-19 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('categoria_licencia', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='conductores/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1565C0', max_length=7)),
                ('imagen_microbus', models.ImageField(blank=True, null=True, upload_to='lineas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('distancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='api.linea')),
            ],
            options={
                'unique_together': {('linea', 'sentido')},
            },
        ),
        migrations.CreateModel(
            name='Microbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cantidad_asientos', models.PositiveIntegerField()),
                ('numero_interno', models.CharField(blank=True, max_length=20)),
                ('fecha_asignacion', models.DateField(default=datetime.date.today)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='microbuses/')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microbuses', to='api.conductor')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linea')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('fuerza_mayor', 'Fuerza Mayor')], default='activo', max_length=20)),
                ('motivo_salida', models.TextField(blank=True, null=True)),
                ('linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linearuta')),
                ('microbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microbus')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidad', models.FloatField(default=0)),
                ('distancia', models.FloatField(default=0)),
                ('tiempo_seg', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='api.recorrido')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='api.linearuta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('linea_ruta', 'orden')},
            },
        ),
    ]
